# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  pod 'Masonry'
target 'LHDiceAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LHDiceAnimation

  target 'LHDiceAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LHDiceAnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
